pino: flat log.level, use "name" for log.logger
elastic/ecs-logging-js pull request #23
Opened 2020-12-22 21:28 UTC by trentm

Per https://github.com/elastic/ecs-logging/blob/c3567a9/spec/spec.json#L21 it
is preferred to have "log.level" as a flat top-level field.

Also, the intent of log.logger is to be the app's logger name, rather
than the name of the logging framework.

2020-12-22 21:32 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-js-mbp%2FPR-23/detail/PR-23/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-js-mbp%2FPR-23/detail/PR-23/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-js-mbp%2FPR-23/detail/PR-23/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-js-mbp%2FPR-23/detail/PR-23/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `Pull request #23 opened`

* Reason: `The PR is not allowed to run in the CI yet`

* Start Time: 2020-12-22T21:28:44.930+0000

* Duration: 3 min 4 sec


* Commit: 0489297202a3690d31478987c8e7e7f8d4fb01b1




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->





### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-js-mbp%2FPR-23/detail/PR-23/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/ecs-logging-js-mbp/pipelines/PR-23/runs/1/steps/81/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/pipelines/ecs-logging-js-mbp/pipelines/PR-23/runs/1/steps/84/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permission</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-12-22T21:31:23.219Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-12-22T21:31:23.222Z]  > git merge f9b2d52e4c5760cda59f30432ba55bd5642507c5 # timeout=10
[2020-12-22T21:31:23.233Z]  > git rev-parse HEAD^{commit} # timeout=10
[2020-12-22T21:31:23.252Z]  > git config core.sparsecheckout # timeout=10
[2020-12-22T21:31:23.275Z]  > git checkout -f 0489297202a3690d31478987c8e7e7f8d4fb01b1 # timeout=15
[2020-12-22T21:31:26.980Z] Commit message: "pino: flat log.level, use "name" for log.logger"
[2020-12-22T21:31:26.980Z] First time build. Skipping changelog.
[2020-12-22T21:31:26.980Z] Cleaning workspace
[2020-12-22T21:31:27.070Z]  > git --version # timeout=10
[2020-12-22T21:31:27.082Z]  > git --version # 'git version 2.17.1'
[2020-12-22T21:31:27.089Z] fatal: bad object 7edba8e3544d4f6700385847f4f4c4daad2361f5
[2020-12-22T21:31:26.985Z]  > git rev-parse --verify HEAD # timeout=10
[2020-12-22T21:31:27.006Z] Resetting working tree
[2020-12-22T21:31:27.006Z]  > git reset --hard # timeout=10
[2020-12-22T21:31:27.023Z]  > git clean -fdx # timeout=10
[2020-12-22T21:31:28.072Z] Masking supported pattern matches of $JOB_GCS_BUCKET or $NOTIFY_TO
[2020-12-22T21:31:28.135Z] Timeout set to expire in 1 hr 0 min
[2020-12-22T21:31:28.163Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2020-12-22T21:31:28.470Z] [INFO] Number of builds to be searched 10
[2020-12-22T21:31:28.606Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2020-12-22T21:31:28.628Z] Running in /var/lib/jenkins/workspace/_nodejs_ecs-logging-js-mbp_PR-23/src/go.elastic.co/apm/ecs-logging-js
[2020-12-22T21:31:28.668Z] [INFO] gitCheckout: Checkout SCM PR-23 with default customisation from the Item.
[2020-12-22T21:31:28.702Z] [INFO] Override default checkout
[2020-12-22T21:31:28.773Z] Sleeping for 10 sec
[2020-12-22T21:31:38.955Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2020-12-22T21:31:39.089Z] Wiping out workspace first.
[2020-12-22T21:31:39.102Z] Cloning the remote Git repository
[2020-12-22T21:31:39.102Z] Using shallow clone with depth 3
[2020-12-22T21:31:39.102Z] Avoid fetching tags
[2020-12-22T21:31:39.124Z] Cloning repository git@github.com:elastic/ecs-logging-js.git
[2020-12-22T21:31:39.157Z]  > git init /var/lib/jenkins/workspace/_nodejs_ecs-logging-js-mbp_PR-23/src/go.elastic.co/apm/ecs-logging-js # timeout=10
[2020-12-22T21:31:39.179Z] Fetching upstream changes from git@github.com:elastic/ecs-logging-js.git
[2020-12-22T21:31:39.180Z]  > git --version # timeout=10
[2020-12-22T21:31:39.195Z]  > git --version # 'git version 2.17.1'
[2020-12-22T21:31:39.195Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-12-22T21:31:39.200Z]  > git fetch --no-tags --progress -- git@github.com:elastic/ecs-logging-js.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2020-12-22T21:31:39.852Z] Cleaning workspace
[2020-12-22T21:31:39.871Z] Using shallow fetch with depth 3
[2020-12-22T21:31:39.871Z] Pruning obsolete local branches
[2020-12-22T21:31:40.421Z] Merging remotes/origin/master commit f9b2d52e4c5760cda59f30432ba55bd5642507c5 into PR head commit 0489297202a3690d31478987c8e7e7f8d4fb01b1
[2020-12-22T21:31:40.478Z] Merge succeeded, producing 0489297202a3690d31478987c8e7e7f8d4fb01b1
[2020-12-22T21:31:40.478Z] Checking out Revision 0489297202a3690d31478987c8e7e7f8d4fb01b1 (PR-23)
[2020-12-22T21:31:40.501Z] Commit message: "pino: flat log.level, use "name" for log.logger"
[2020-12-22T21:31:40.501Z] Cleaning workspace
[2020-12-22T21:31:40.547Z]  > git --version # timeout=10
[2020-12-22T21:31:40.555Z]  > git --version # 'git version 2.17.1'
[2020-12-22T21:31:40.559Z] fatal: bad object 7edba8e3544d4f6700385847f4f4c4daad2361f5
[2020-12-22T21:31:39.829Z]  > git config remote.origin.url git@github.com:elastic/ecs-logging-js.git # timeout=10
[2020-12-22T21:31:39.833Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-12-22T21:31:39.848Z]  > git config remote.origin.url git@github.com:elastic/ecs-logging-js.git # timeout=10
[2020-12-22T21:31:39.857Z]  > git rev-parse --verify HEAD # timeout=10
[2020-12-22T21:31:39.862Z] No valid HEAD. Skipping the resetting
[2020-12-22T21:31:39.862Z]  > git clean -fdx # timeout=10
[2020-12-22T21:31:39.877Z] Fetching upstream changes from git@github.com:elastic/ecs-logging-js.git
[2020-12-22T21:31:39.877Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-12-22T21:31:39.881Z]  > git fetch --no-tags --progress --prune -- git@github.com:elastic/ecs-logging-js.git +refs/pull/23/head:refs/remotes/origin/PR-23 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2020-12-22T21:31:40.426Z]  > git config core.sparsecheckout # timeout=10
[2020-12-22T21:31:40.430Z]  > git checkout -f 0489297202a3690d31478987c8e7e7f8d4fb01b1 # timeout=15
[2020-12-22T21:31:40.451Z]  > git remote # timeout=10
[2020-12-22T21:31:40.454Z]  > git config --get remote.origin.url # timeout=10
[2020-12-22T21:31:40.458Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-12-22T21:31:40.462Z]  > git merge f9b2d52e4c5760cda59f30432ba55bd5642507c5 # timeout=10
[2020-12-22T21:31:40.474Z]  > git rev-parse HEAD^{commit} # timeout=10
[2020-12-22T21:31:40.483Z]  > git config core.sparsecheckout # timeout=10
[2020-12-22T21:31:40.486Z]  > git checkout -f 0489297202a3690d31478987c8e7e7f8d4fb01b1 # timeout=15
[2020-12-22T21:31:40.506Z]  > git rev-parse  [...]

2020-12-23 00:47 UTC, trentm commented
jenkins run the tests

2020-12-23 16:32 UTC, delvedor approved these changes
LGTM

2020-12-23 16:57 UTC, delvedor requested changes
I've just noticed, the [serializer](https://github.com/elastic/ecs-logging-js/blob/master/helpers/serializer.js) needs to be updated as well.
We should add a test as well, given that CI didn't complain.

2020-12-24 00:35 UTC, trentm commented
Yup, that breaks as expected:

```
16:34:06  + run_install loggers/winston
16:34:06  + echo '=== Installing dependencies in loggers/winston ==='
16:34:06  === Installing dependencies in loggers/winston ===
16:34:06  + npm --prefix /var/lib/jenkins/workspace/_nodejs_ecs-logging-js-mbp_PR-23/src/go.elastic.co/apm/ecs-logging-js/loggers/winston install
16:34:08  npm WARN deprecated fsevents@2.1.3: Please update to v 2.2.x
16:34:11  npm ERR! code ETARGET
16:34:11  npm ERR! notarget No matching version found for @elastic/ecs-helpers@^0.3.0.
16:34:11  npm ERR! notarget In most cases you or one of your dependencies are requesting
```

2020-12-24 00:43 UTC, trentm commented
I've moved the helpers package change out to https://github.com/elastic/ecs-logging-js/pull/25 to handle and publish that first.

2021-01-05 23:23 UTC, trentm commented
Sorry for the force-push. Bad habit that I'm trying to break.

2021-01-06 00:42 UTC, trentm commented
I tagged @astorm as well in case you are interested in reviewing. Not worries if not.

2021-01-06 17:44 UTC, astorm approved these changes
approving -- it does the thing 👍

2021-01-06 18:20 UTC, merged

2021-01-06 18:24 UTC, trentm commented
Published:
- @elastic/ecs-pino-format@0.2.0
- @elastic/ecs-winston-format@0.3.0
- @elastic/ecs-morgan-format@0.3.0